# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2024-06-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('inn', models.IntegerField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ИНН')),
                ('family_name', models.CharField(max_length=90, verbose_name='Фамилия')),
                ('human_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=65, verbose_name='Отчество')),
                ('gender', models.BooleanField(default=True, verbose_name='Пол')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Категория должности')),
                ('id_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.Vacancy')),
            ],
        ),
    ]
