# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2024-06-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_human_vacancycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='inn',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ИНН'),
        ),
    ]
